[profile.default]
evm_version = 'cancun'
src = 'src'
out = 'out'
libs = ['lib']
#block number
block_number = 100
# The block timestamp in tests
block_timestamp = 1500
# allow ffi
ffi = true
# gas limit in tests
gas_limit = 30000000
# optimizer
optimizer = true
# optimizer runs
optimizer_runs = 200
# use via-ir optimizer
# via_ir = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
